name: Build PR with Maven

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout commits
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: zephyr_eclipse_p2_repo
        path: maven/repository/target/repository

    - name: Upload to AWS S3
      run: |
        echo "publish latest docs"
        aws s3 sync  --quiet maven/repository/target/repository s3://builds.zephyrproject.org/eclipse-plugin --delete
